#! Lo que estoy haciendo es que el microservicio estudiante se conecte al servidor de configuración para obtener la configuración de la aplicación.
spring:
  application:
    name: msvc-student
  config:
    import: optional:configserver:http://localhost:8888
